export const STOIC_QUOTES = [
  'A vida fica mais seria quando cabe diante dos olhos.',
  'O tempo parece amplo ate ganhar contorno.',
  'Semanas passam mesmo quando nada e decidido.',
  'Viver e preencher o irreversivel.',
  'O futuro nao e estoque; e limite.',
  'Cada semana gasta ja pertence ao silencio.',
  'A clareza comeca quando o tempo deixa de ser abstrato.',
  'O relogio mede horas; a vida cobra escolhas.',
  'A finitude nao diminui a vida; da forma a ela.',
  'Nem todo atraso e visivel, mas todo atraso custa.',
  'O tempo nao se perde de uma vez, mas em parcelas.',
  'Quem ve o tempo com nitidez escolhe com menos vaidade.',
  'O amanha e uma hipotese, nao um direito.',
  'O tempo nao precisa gritar para ser definitivo.',
  'A urgencia verdadeira e silenciosa.',
  'O presente melhora quando deixa de se imaginar infinito.',
  'Ha uma disciplina em lembrar que o tempo termina.',
  'O irreversivel e o professor mais sobrio.',
  'A forma visivel do tempo corrige fantasias.',
  'A verdade do tempo e austera, mas limpa.',
  'O valor de uma semana depende de quem a habita.',
  'O tempo nao negocia com distracoes.',
  'A finitude organiza o que a abundancia confunde.',
  'Contar semanas e uma forma de devolver peso ao viver.',
  'A morte nao precisa ser pensada com medo para ser util.',
  'A lucidez temporal reduz a importancia do superfluo.',
  'O presente ganha densidade quando o fim nao e omitido.',
  'Viver bem exige alguma familiaridade com o limite.',
  'Ha uma etica em olhar para o calendario com sinceridade.',
  'O tempo restante nao e um premio; e uma incumbencia.',
  'A vida pede menos abstracao e mais presenca.',
  'A duracao importa, mas a direcao importa mais.',
  'Ha calendarios que informam datas; este informa mortalidade.',
  'O tempo visivel se torna quase moral.',
  'Ver o tempo nao resolve tudo; apenas impede algumas mentiras.',
  'O fim de uma vida tambem comeca em uma semana qualquer.',
  'Ha grandeza em viver sem fingir eternidade.',
  'O numero nao empobrece a vida; torna-a concreta.',
  'O que voce ama precisa caber no tempo que existe.',
  'O homem se perde menos quando mede o caminho.',
  'O essencial costuma reaparecer quando o tempo e desenhado.',
  'O presente e mais nobre quando nao depende de negacao.',
  'A mortalidade e amarga, mas corrige a escala.',
  'O calendario pode ser um instrumento de filosofia.',
  'Uma semana bem usada vale mais que um mes disperso.',
  'O tempo restante nao pede panico; pede forma.',
  'O tempo tem uma delicadeza cruel: passa sem alarde.',
  'A realidade se torna mais legivel quando o tempo aparece inteiro.',
  'A finitude pode ser uma arquitetura, nao apenas uma ameaca.',
  'Quem encara o limite ganha um criterio.',
  'Nada amadurece sem custo temporal.',
  'O tempo e um bem estranho: so se entende quando diminui.',
  'A vida nao e um ensaio com agenda flexivel.',
  'A mortalidade e o enquadramento invisivel de toda escolha.',
  'A clareza temporal e um antidoto contra a dispersao.',
  'Cada capitulo de sete anos muda a pergunta central da vida.',
  'A existencia tem ritmo, nao apenas extensao.',
  'O homem prudente honra o que o tempo nao repoe.',
  'O limite devolve valor ao instante.',
  'A seriedade nao esta em contar semanas, mas em honra-las.',
  'O tempo nao castiga; apenas nao espera.',
  'A contemplacao do fim pode salvar o meio.',
  'O que voce repete se torna biografia.',
  'A responsabilidade cresce quando o tempo ganha borda.',
  'Ha uma liberdade em aceitar que tudo nao cabera.',
  'O limite faz nascer a escolha verdadeira.',
  'O adiamento e o luxo favorito de quem esqueceu a morte.',
  'O tempo que resta pede menos promessa e mais presenca.',
  'A clareza vem quando o calendario deixa de ser decoracao.',
  'A mortalidade torna o amor mais serio e o ego menor.',
  'O homem que lembra do fim trata melhor o meio.',
  'O numero exato nao importa tanto quanto a estrutura finita.',
  'Ha um consolo sobrio em reconhecer o limite.',
  'A semana presente pede menos teoria e mais decisao.',
  'O tempo visivel e um chamado a hierarquia.',
] as const

export function pickStoicQuote(random: () => number = Math.random) {
  const index = Math.floor(random() * STOIC_QUOTES.length)

  return STOIC_QUOTES[index] ?? STOIC_QUOTES[0]
}

