export const STOIC_QUOTES = [
  'A vida fica mais séria quando cabe diante dos olhos.',
  'O tempo parece amplo até ganhar contorno.',
  'Semanas passam mesmo quando nada é decidido.',
  'Viver é preencher o irreversível.',
  'O futuro não é estoque; é limite.',
  'Cada semana gasta já pertence ao silêncio.',
  'A clareza começa quando o tempo deixa de ser abstrato.',
  'O relógio mede horas; a vida cobra escolhas.',
  'A finitude não diminui a vida; dá forma a ela.',
  'Nem todo atraso é visível, mas todo atraso custa.',
  'O tempo não se perde de uma vez, mas em parcelas.',
  'Quem vê o tempo com nitidez escolhe com menos vaidade.',
  'O amanhã é uma hipótese, não um direito.',
  'O tempo não precisa gritar para ser definitivo.',
  'A urgência verdadeira é silenciosa.',
  'O presente melhora quando deixa de se imaginar infinito.',
  'Há uma disciplina em lembrar que o tempo termina.',
  'O irreversível é o professor mais sóbrio.',
  'A forma visível do tempo corrige fantasias.',
  'A verdade do tempo é austera, mas limpa.',
  'O valor de uma semana depende de quem a habita.',
  'O tempo não negocia com distrações.',
  'A finitude organiza o que a abundância confunde.',
  'Contar semanas é uma forma de devolver peso ao viver.',
  'A morte não precisa ser pensada com medo para ser útil.',
  'A lucidez temporal reduz a importância do supérfluo.',
  'O presente ganha densidade quando o fim não é omitido.',
  'Viver bem exige alguma familiaridade com o limite.',
  'Há uma ética em olhar para o calendário com sinceridade.',
  'O tempo restante não é um prêmio; é uma incumbência.',
  'A vida pede menos abstração e mais presença.',
  'A duração importa, mas a direção importa mais.',
  'Há calendários que informam datas; este informa mortalidade.',
  'O tempo visível se torna quase moral.',
  'Ver o tempo não resolve tudo; apenas impede algumas mentiras.',
  'O fim de uma vida também começa em uma semana qualquer.',
  'Há grandeza em viver sem fingir eternidade.',
  'O número não empobrece a vida; torna-a concreta.',
  'O que você ama precisa caber no tempo que existe.',
  'O homem se perde menos quando mede o caminho.',
  'O essencial costuma reaparecer quando o tempo é desenhado.',
  'O presente é mais nobre quando não depende de negação.',
  'A mortalidade é amarga, mas corrige a escala.',
  'O calendário pode ser um instrumento de filosofia.',
  'Uma semana bem usada vale mais que um mês disperso.',
  'O tempo restante não pede pânico; pede forma.',
  'O tempo tem uma delicadeza cruel: passa sem alarde.',
  'A realidade se torna mais legível quando o tempo aparece inteiro.',
  'A finitude pode ser uma arquitetura, não apenas uma ameaça.',
  'Quem encara o limite ganha um critério.',
  'Nada amadurece sem custo temporal.',
  'O tempo é um bem estranho: só se entende quando diminui.',
  'A vida não é um ensaio com agenda flexível.',
  'A mortalidade é o enquadramento invisível de toda escolha.',
  'A clareza temporal é um antídoto contra a dispersão.',
  'Cada capítulo de sete anos muda a pergunta central da vida.',
  'A existência tem ritmo, não apenas extensão.',
  'O homem prudente honra o que o tempo não repõe.',
  'O limite devolve valor ao instante.',
  'A seriedade não está em contar semanas, mas em honrá-las.',
  'O tempo não castiga; apenas não espera.',
  'A contemplação do fim pode salvar o meio.',
  'O que você repete se torna biografia.',
  'A responsabilidade cresce quando o tempo ganha borda.',
  'Há uma liberdade em aceitar que tudo não caberá.',
  'O limite faz nascer a escolha verdadeira.',
  'O adiamento é o luxo favorito de quem esqueceu a morte.',
  'O tempo que resta pede menos promessa e mais presença.',
  'A clareza vem quando o calendário deixa de ser decoração.',
  'A mortalidade torna o amor mais sério e o ego menor.',
  'O homem que lembra do fim trata melhor o meio.',
  'O número exato não importa tanto quanto a estrutura finita.',
  'Há um consolo sóbrio em reconhecer o limite.',
  'A semana presente pede menos teoria e mais decisão.',
  'O tempo visível é um chamado à hierarquia.',
] as const

export function pickStoicQuote(random: () => number = Math.random) {
  const index = Math.floor(random() * STOIC_QUOTES.length)

  return STOIC_QUOTES[index] ?? STOIC_QUOTES[0]
}
